tab <- read.table("household_power_consumption.txt",fill=TRUE, header = FALSE,sep=";",skip=(grep("1/2/2007", readLines("household_power_consumption.txt"))-1),nrows=2880)
names(tab)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
tab$Date1<-(as.Date(as.character(tab$Date),"%d/%m/%Y"))
tab$timestamp=format(as.POSIXct(paste(tab$Date1, tab$Time)), "%d/%m/%Y %H:%M:%S")
png(filename="plot4.png", width=480 ,height = 480)
par(oma=c(1,0,1,0))
split.screen(c(2,2))
screen(1)
plot(strptime(tab$timestamp, format="%d/%m/%Y %H:%M:%S"),tab$Global_active_power,cex.lab=0.85,ylab="Global Active Power ", xlab="",type="l")
screen(2)
plot(strptime(tab$timestamp, format="%d/%m/%Y %H:%M:%S"),tab$Voltage,ylab="Voltage",cex.lab=.85, xlab="datetime",type="l")
screen(3)
split.screen(c(1,1))
screen(5)
with(tab,plot(strptime(tab$timestamp, format="%d/%m/%Y %H:%M:%S"),tab$Sub_metering_1,cex.lab=.85,col="black",type="l",ylab="Energy Sub metering",xlab="",ylim=c(0,max(tab$Sub_metering_1))))
screen(5,new=FALSE)
with(tab,plot(strptime(tab$timestamp, format="%d/%m/%Y %H:%M:%S"),tab$Sub_metering_2,cex.lab=.85,col="red",type="l",ylab="",xlab="",ylim=c(0,max(tab$Sub_metering_1))))
screen(5,new=FALSE)
with(tab,plot(strptime(tab$timestamp, format="%d/%m/%Y %H:%M:%S"),tab$Sub_metering_3,cex.lab=.85,col="blue",type="l",ylab="",xlab="",ylim=c(0,max(tab$Sub_metering_1))))
legend("topright",lty=c(1,1,1),text.font = 0.1,cex=0.64,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
close.screen(5) 
screen(4)
plot(strptime(tab$timestamp, format="%d/%m/%Y %H:%M:%S"),tab$Global_reactive_power,cex.lab=.85,ylab="Global_reactive_power", xlab="datetime",type="l")
close.screen(all=TRUE)
dev.off()

