tab <- read.table("household_power_consumption.txt",fill=TRUE, header = FALSE,sep=";",skip=(grep("1/2/2007", readLines("household_power_consumption.txt"))-1),nrows=2880)
names(tab)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
tab$Date1<-(as.Date(as.character(tab$Date),"%d/%m/%Y"))
tab$timestamp=format(as.POSIXct(paste(tab$Date1, tab$Time)), "%d/%m/%Y %H:%M:%S")
png(filename="plot3.png", width=480 ,height = 480)
par(oma=c(1,1,1,1))
par(mar=c(5,4,4,2) + 0.1)   
split.screen(c(1,1))
with(tab,plot(strptime(tab$timestamp, format="%d/%m/%Y %H:%M:%S"),tab$Sub_metering_1,col="black",type="l",ylab="Energy Sub metering",xlab="",ylim=c(0,max(tab$Sub_metering_1))))
screen(1,new=FALSE)
with(tab,plot(strptime(tab$timestamp, format="%d/%m/%Y %H:%M:%S"),tab$Sub_metering_2,col="red",type="l",ylab="",xlab="",ylim=c(0,max(tab$Sub_metering_1))))
screen(1,new=FALSE)
with(tab,plot(strptime(tab$timestamp, format="%d/%m/%Y %H:%M:%S"),tab$Sub_metering_3,col="blue",type="l",ylab="",xlab="",ylim=c(0,max(tab$Sub_metering_1))))
legend("topright",lty=c(1,1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
close.screen(all = TRUE) 
dev.off()
